# Generated by Django 4.2.5 on 2023-10-03 17:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link_to_original', models.BooleanField(default=False)),
                ('generate_expiring_links', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Thumbnail size',
                'verbose_name_plural': 'Thumbnail sizes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_api.accounttier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TierConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_expiring_links', models.BooleanField(default=False)),
                ('expiration_seconds', models.PositiveBigIntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)])),
                ('tier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='image_api.accounttier')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/dynamic/')),
                ('image_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_images', to='image_api.uploadedimage')),
            ],
        ),
        migrations.AddField(
            model_name='accounttier',
            name='thumbnail_sizes',
            field=models.ManyToManyField(blank=True, to='image_api.thumbnailsettings'),
        ),
    ]
